### ISSUE TITLE
Questions about licensing, to use your code in my project.

### ISSUE THREAD

**Issue by DerHirschi** [4x1md/qth_locator_functions#2]
I would like to integrate your code into my project also under MIT License. Is it OK for you if your license is attached as comment and you are signed as the author in the respective functions?
Or should I insert the license separately as a text file?

Here is how i would integrate it so far:
Greetings and 73.. 

[loc_fnc.txt](https://github.com/4x1md/qth_locator_functions/files/11602506/loc_fnc.txt)

**Comment by DerHirschi** [comment]
I've added your original repo to the docs folder in my project and author, source and location to your LICENSE file in the function comment.
I think you should be fine with that.

**Comment by 4x1md** [comment]
Hello,
Yes, looks fine. Since then my callsign changed from 4X5DM to 4X1MD.
I'm curious about the project you create.
73
Dmitry

**Comment by DerHirschi** [comment]
Unfortunately, there is only old terminal software and hardly any for Linux. That's why I decided to write an AX25Termial myself. I'm just an amateur scripter so some of the code is a bit crapy and not optimal.

https://github.com/DerHirschi/AX25_POPT

73 Manuel ( I'm not a HAM but we have a AX25 Network on CB Radio here in Germany and Europe (CB0SAW is my Node  and u can reach them over AXIP: cb0saw.ddnss.de U 8093) )
